# Generated by Django 5.1.2 on 2025-10-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
    ]
