# Generated by Django 5.1.2 on 2025-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('confirmations', models.IntegerField(default=0)),
                ('min_deposit_amount', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('asset', models.ManyToManyField(blank=True, null=True, related_name='networks', to='assets.asset')),
            ],
            options={
                'db_table': 'networks',
            },
        ),
    ]
