# Generated by Django 5.1.2 on 2025-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='network',
            field=models.ManyToManyField(blank=True, null=True, related_name='networks', to='assets.network'),
        ),
    ]
