# Generated by Django 5.1.2 on 2025-10-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_network_asset_asset_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='network',
        ),
        migrations.AddField(
            model_name='asset',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='assets.network'),
        ),
    ]
