# Generated by Django 5.1.2 on 2025-10-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_network_asset_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='network',
        ),
        migrations.AddField(
            model_name='asset',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.network'),
        ),
    ]
