# Generated by Django 5.1.2 on 2025-10-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_asset_network_asset_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='min_deposit_time',
            field=models.IntegerField(default=0),
        ),
    ]
