# Generated by Django 5.2.7 on 2025-11-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_apr_high_remove_asset_apr_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='assets.network'),
        ),
        migrations.AddField(
            model_name='balance',
            name='private',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='public',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
