# Generated by Django 5.2.7 on 2025-11-05 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_balance_network_balance_private_balance_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(blank=True, max_length=10, null=True)),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('lp', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('prev_close_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('max_24h', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('min_24h', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('perc_24', models.FloatField(default=0)),
                ('value_in_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'db_table': 'quotes',
                'unique_together': {('asset', 'interval')},
            },
        ),
    ]
