# Generated by Django 6.0 on 2025-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='fiat',
            field=models.BooleanField(default=False),
        ),
    ]
