# Generated by Django 6.0 on 2025-12-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_fiat'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='staking',
            field=models.BooleanField(default=False),
        ),
    ]
