# Generated by Django 6.0 on 2025-12-28 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0014_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StakePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('rewards', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_staked_pend', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stake_pend_tx', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staked_pending',
            },
        ),
        migrations.CreateModel(
            name='StakeTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_of_exit', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('rewards', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('type', models.CharField(default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_staked', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_staketx', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staked_tx',
            },
        ),
        migrations.CreateModel(
            name='StakingRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_reward_st', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reward_st', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staking_reward',
            },
        ),
    ]
